version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: petshop_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: petshop
      POSTGRES_PASSWORD: petshop
      POSTGRES_DB: petshop_db
    ports:
      - "5432:5432"
    volumes:
      - petshop_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: petshop_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  petshop_pgdata:
